/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as InspiracoesRouteImport } from './routes/inspiracoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AreaAtendidaRouteImport } from './routes/area-atendida'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendarSucessoRouteImport } from './routes/agendar.sucesso'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const InspiracoesRoute = InspiracoesRouteImport.update({
  id: '/inspiracoes',
  path: '/inspiracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAtendidaRoute = AreaAtendidaRouteImport.update({
  id: '/area-atendida',
  path: '/area-atendida',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarSucessoRoute = AgendarSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => AgendarRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/area-atendida': typeof AreaAtendidaRoute
  '/contato': typeof ContatoRoute
  '/inspiracoes': typeof InspiracoesRoute
  '/instalar': typeof InstalarRoute
  '/mcp': typeof McpRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agendar/sucesso': typeof AgendarSucessoRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/area-atendida': typeof AreaAtendidaRoute
  '/contato': typeof ContatoRoute
  '/inspiracoes': typeof InspiracoesRoute
  '/instalar': typeof InstalarRoute
  '/mcp': typeof McpRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agendar/sucesso': typeof AgendarSucessoRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRouteWithChildren
  '/area-atendida': typeof AreaAtendidaRoute
  '/contato': typeof ContatoRoute
  '/inspiracoes': typeof InspiracoesRoute
  '/instalar': typeof InstalarRoute
  '/mcp': typeof McpRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agendar/sucesso': typeof AgendarSucessoRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/area-atendida'
    | '/contato'
    | '/inspiracoes'
    | '/instalar'
    | '/mcp'
    | '/servicos'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agendar/sucesso'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/area-atendida'
    | '/contato'
    | '/inspiracoes'
    | '/instalar'
    | '/mcp'
    | '/servicos'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agendar/sucesso'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/area-atendida'
    | '/contato'
    | '/inspiracoes'
    | '/instalar'
    | '/mcp'
    | '/servicos'
    | '/sobre'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agendar/sucesso'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRouteWithChildren
  AreaAtendidaRoute: typeof AreaAtendidaRoute
  ContatoRoute: typeof ContatoRoute
  InspiracoesRoute: typeof InspiracoesRoute
  InstalarRoute: typeof InstalarRoute
  McpRoute: typeof McpRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiracoes': {
      id: '/inspiracoes'
      path: '/inspiracoes'
      fullPath: '/inspiracoes'
      preLoaderRoute: typeof InspiracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-atendida': {
      id: '/area-atendida'
      path: '/area-atendida'
      fullPath: '/area-atendida'
      preLoaderRoute: typeof AreaAtendidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/sucesso': {
      id: '/agendar/sucesso'
      path: '/sucesso'
      fullPath: '/agendar/sucesso'
      preLoaderRoute: typeof AgendarSucessoRouteImport
      parentRoute: typeof AgendarRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgendarRouteChildren {
  AgendarSucessoRoute: typeof AgendarSucessoRoute
}

const AgendarRouteChildren: AgendarRouteChildren = {
  AgendarSucessoRoute: AgendarSucessoRoute,
}

const AgendarRouteWithChildren =
  AgendarRoute._addFileChildren(AgendarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRouteWithChildren,
  AreaAtendidaRoute: AreaAtendidaRoute,
  ContatoRoute: ContatoRoute,
  InspiracoesRoute: InspiracoesRoute,
  InstalarRoute: InstalarRoute,
  McpRoute: McpRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
